using System.Net.Http;

using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace PublisherWeb.seedWork
{
    /// <summary>
    /// Base Class For ApiClient that is generated by swagger.
    /// </summary>
    public class ApiClientBase
    {
       // private readonly IOptions _settings;
        private readonly HttpClient _httpClient;
        private readonly ILogger _logger;
        public ApiClientBase(HttpClient httpClient, ILogger logger)
        {
            _httpClient = httpClient;
           // _settings = settings;
            _logger = logger;
        }
    }
}